#include "probability/ztable.h"

// These constants are defined in the file generated by the ztable creation tool
extern const float ZTABLE_MINIMUM;
extern const float ZTABLE_RANGE;
extern const int ZTABLE_SAMPLES;
extern const float ztable[];

float _ztableLookup(float z)
{
  const int sampleIndex = (z - ZTABLE_MINIMUM) / ZTABLE_RANGE * ZTABLE_SAMPLES;

  // Lookup the zscore, clamping the value to 0 or 1 if it is out of the table
  float zscore;
  if (sampleIndex < 0)
    zscore = 0;

  else if (sampleIndex >= ZTABLE_SAMPLES)
    zscore = 1;

  else
    zscore = ztable[sampleIndex];

  return zscore;
}

float ztest(float mu, float sigma, float z)
{
  const float normalized = (z - mu) / sigma;
  return _ztableLookup(normalized);
}

float ztestBounded(float mu, float sigma, float z, float delta) {
  const float z1 = ztest(mu, sigma, z - delta);
  const float z2 = ztest(mu, sigma, z + delta);

  // Return the difference between the larger and smaller probabilities
  // TODO In theory this test should be redundant, but I haven't done the math
  return z1 > z2 ? z1 - z2 : z2 - z1;
}

